#!/usr/bin/env python3
"""Generate packed, anti-aliased text glyphs for the firmware.

Mirrors scripts/build_aircraft_icons.py: glyphs are rasterised at build time to
4-bit alpha, two pixels per byte with the high nibble first, and drawn at runtime
by Canvas::blendAlphaMask4 -- the same primitive the rotated aircraft icons
already use. Nothing new is needed on the device beyond a glyph table.

Each glyph's data is padded to a whole number of bytes so it can be handed to
blendAlphaMask4 directly, which treats its pointer as pixel index 0.

Positions are stored relative to the text origin's top-left, so drawing needs no
ascent arithmetic at runtime: advance the pen by `advance`, and blit each glyph
at (pen + bearingX, top + bearingY).

    ./scripts/build_font_atlas.py assets/fonts/RobotoCondensed-Regular.ttf
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from PIL import Image, ImageFont

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src" / "panel_font_aa.inc"

FIRST_CHAR = 32
LAST_CHAR = 126

# (identifier, pixel size). Sized to replace the 5x7 and 8x11 bitmap faces.
SIZES = (("Small", 13), ("Large", 20))


def pack_alpha4(gray: bytes) -> bytes:
    """8-bit grey -> 4-bit alpha, two pixels per byte, high nibble first."""
    out = bytearray((len(gray) + 1) // 2)
    for index, value in enumerate(gray):
        nibble = (value * 15 + 127) // 255
        if index & 1:
            out[index >> 1] |= nibble
        else:
            out[index >> 1] |= nibble << 4
    return bytes(out)


def build_size(font_path: Path, pixel_size: int):
    font = ImageFont.truetype(str(font_path), pixel_size)
    ascent, descent = font.getmetrics()
    blob = bytearray()
    glyphs = []

    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        ch = chr(code)
        bbox = font.getbbox(ch)
        advance = int(round(font.getlength(ch)))
        if bbox is None:
            glyphs.append((len(blob), 0, 0, 0, 0, advance))
            continue
        x0, y0, x1, y1 = bbox
        w, h = max(0, x1 - x0), max(0, y1 - y0)
        if w == 0 or h == 0:  # space and friends
            glyphs.append((len(blob), 0, 0, 0, 0, advance))
            continue

        # getmask() already returns just the glyph's ink, so it is used as-is.
        # Cropping it by the bbox would discard the first y0 rows of real pixels
        # -- which silently produced glyphs holding only their lower half.
        # The bbox supplies placement only.
        mask = font.getmask(ch, mode="L")
        cropped = Image.frombytes("L", mask.size, bytes(mask))
        w, h = cropped.size
        if w == 0 or h == 0:
            glyphs.append((len(blob), 0, 0, 0, 0, advance))
            continue

        offset = len(blob)
        blob += pack_alpha4(cropped.tobytes())
        glyphs.append((offset, w, h, x0, y0, advance))

    return {
        "ascent": ascent,
        "descent": descent,
        "line_height": ascent + descent,
        "glyphs": glyphs,
        "blob": bytes(blob),
    }


def emit(name: str, data: dict) -> str:
    lines = [f"// {name}: {len(data['blob'])} bytes of packed alpha"]
    lines.append(f"static constexpr uint8_t k{name}LineHeight = {data['line_height']};")
    lines.append(f"static constexpr uint8_t k{name}Ascent = {data['ascent']};")
    lines.append(f"static const uint8_t k{name}Bitmap[] PROGMEM = {{")
    blob = data["blob"]
    for start in range(0, len(blob), 16):
        chunk = ", ".join(f"0x{b:02X}" for b in blob[start:start + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append(f"static const AaGlyph k{name}Glyphs[] = {{")
    for offset, w, h, bx, by, adv in data["glyphs"]:
        lines.append(f"    {{{offset}, {w}, {h}, {bx}, {by}, {adv}}},")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("font", type=Path)
    ap.add_argument("--output", type=Path, default=OUTPUT)
    args = ap.parse_args()

    if not args.font.exists():
        sys.exit(f"font not found: {args.font}")

    parts = [
        "// Generated by scripts/build_font_atlas.py. Do not edit manually.",
        f"// Source: {args.font.name}",
        "",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "// Portable between the firmware and tools/preview, which builds this",
        "// natively and has no Arduino headers.",
        "#if defined(ARDUINO) || defined(ESP_PLATFORM)",
        "#include <pgmspace.h>",
        "#elif !defined(PROGMEM)",
        "#define PROGMEM",
        "#endif",
        "",
        "namespace PanelFontAa {",
        "",
        "struct AaGlyph {",
        "    uint32_t offset;   // byte offset into the bitmap blob",
        "    uint8_t width;",
        "    uint8_t height;",
        "    int8_t bearingX;   // from the pen position",
        "    int8_t bearingY;   // from the text top, so no ascent maths at runtime",
        "    uint8_t advance;",
        "};",
        "",
        f"static constexpr uint8_t kFirstChar = {FIRST_CHAR};",
        f"static constexpr uint8_t kLastChar = {LAST_CHAR};",
        "",
    ]
    total = 0
    for name, size in SIZES:
        data = build_size(args.font, size)
        total += len(data["blob"])
        parts.append(emit(name, data))
        parts.append("")
        print(f"  {name:6s} {size:2d}px  line_height={data['line_height']:2d}  "
              f"{len(data['blob']):6d} bytes")
    parts.append("}  // namespace PanelFontAa")

    args.output.write_text("\n".join(parts) + "\n")
    print(f"  total {total} bytes -> {args.output.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
